sonar.projectKey=prolance-frontend-daxa
sonar.projectName=Prolance :: Frontend (Angular daxa)
sonar.projectVersion=1.6.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**,**/coverage/**,**/.angular/**

sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/daxa/lcov.info
sonar.typescript.lcov.reportPaths=coverage/daxa/lcov.info
