# ?? Server ????????????????????????????????????????????????????????????????????
server.port=8083

# ?? Application name ??????????????????????????????????????????????????????????
spring.application.name=microservice-contract

# ?? DataSource ????????????????????????????????????????????????????????????????
spring.datasource.url=jdbc:mysql://localhost:3306/prolance_contracts?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ?? JPA / Hibernate ???????????????????????????????????????????????????????????
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ?? Eureka Client ?????????????????????????????????????????????????????????????
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# ?? Actuator ??????????????????????????????????????????????????????????????????
management.endpoints.web.exposure.include=health,info,metrics

# ?? Error Handling ????????????????????????????????????????????????????????????
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always

# ?? Mailtrap Sandbox ??????????????????????????????????????????????????????????
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=eb367555f7faf4
spring.mail.password=1a9dd4c484953f

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ?? App config ????????????????????????????????????????????????????????????????
app.mail.from=ProLance <noreply@prolance.com>
app.base-url=http://localhost:8083
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# ?? Proposal service URL for Feign ???????????????????????????????????????????
proposal.service.url=http://localhost:8092/freelance1