spring.application.name=gateway-service
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.routes[0].id=reviews-service
spring.cloud.gateway.routes[0].uri=lb://reviews-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/reviews/**

spring.cloud.gateway.routes[1].id=forum-service
spring.cloud.gateway.routes[1].uri=lb://forum-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/posts/**,/api/replies/**