apiVersion: v1
kind: Namespace
metadata:
  name: prolance
  labels:
    app.kubernetes.io/name: prolance
    monitoring: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: monitoring
